MODEL:
  TYPE: 
  NAME: eva02_l_text
  PRETRAIN_PATH: '/home/jin/code/MADE/weights/eva02_large_patch14_clip_224/open_clip_model.safetensors'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  DIST_TRAIN: False
  ADD_TEXT: True
  TEXT_DIMS: [ 512, ]
  TEXT:
    METHOD: "cocoop"
    CLIP_NAME: ''
    N_CTX: 32
    ENABLE_MASK: True
    ATTN_MASK_RATIO: 0.0
    TEMP: 0.07
    ITC_W: 0.005
    PROXY_GATE_ON: False
    PROXY_KEEP_RATIO: 0.5
    PROXY_GATE_TEMP: 1.0
    PROXY_GATE_MIN: 0.0
    PROXY_GATE_APPLY: "t1,t2"
    PROXY_DETACH_PROXY: True
    PROXY_DETACH_SCORE: False


DATA:
  IMG_HEIGHT: 224
  IMG_WIDTH: 224
  DATASET: 'celeb_light'
  RANDOM_NOISE: False

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 2e-5
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 2

TEST:
  WEIGHT: ''
  TYPE: 'image_only'
  FEAT_NORM: 'yes'
OUTPUT_DIR: '../MADE/logs/celeb_light/text/proxy'


